#!/bin/bash

ctrl_c()
{
	cd .. &&
	rm -rf .cpp_repl
	echo ""
	exit
}

start()
{
	trap ctrl_c INT
	mkdir .cpp_repl && 
	cd .cpp_repl &&
	touch execute.cpp &&
	echo "#include <iostream>" > execute.cpp
	echo "using namespace std; int main(){" >> execute.cpp
}

compile_and_run()
{
	echo "}" >> execute.cpp
	g++ execute.cpp &&
	./a.out &&
	echo ""
	clean
}

execute_command()
{
	echo "$1" >> execute.cpp
	compile_and_run
}

clean()
{
	echo "#include <iostream>" > execute.cpp
	echo "using namespace std; int main(){ " >> execute.cpp
}

start
while :; do
	read -p "λ " command
	execute_command "$command"
done